### ISSUE TITLE
How to set cperl-mode to indent parens as block

### ISSUE THREAD

**Issue by mpkh** [jrockway/cperl-mode#14]
Hello I  want to write code blocks alike following:

``` perl
xxx {
  yyy
  }
```

I saw this

``` lisp
(defcustom cperl-indent-parens-as-block nil
  "*Non-nil means that non-block ()-, {}- and []-groups are indented as blocks,
but for trailing \",\" inside the group, which won't increase indentation.
One should tune up `cperl-close-paren-offset' as well."
  :type 'boolean
  :group 'cperl-indentation-details)
```

And was trying to add this:

``` lisp
(setq cperl-indent-parens-as-block t)
```

https://github.com/Cynede/emacs.d/commit/a93298c882dbd5170636df7c7e53711bb1b94ba0

I expected it will indent closing block bracket but it doesn't. And I can't detect any other changes.

When I set 

``` lisp
(defcustom cperl-indent-parens-as-block t
    ...
```

in code it doesn't indent closing block bracket too.

**Comment by CeleritasCelery** [comment]
https://www.emacswiki.org/emacs/IndentingPerl

**Comment by mpkh** [comment]
sorry, outdated =)
