### ISSUE TITLE
How to make cperl-indent-region not change any indentation within here-docs?

### ISSUE THREAD

**Issue by kaushalmodi** [jrockway/cperl-mode#22]
Hi,

How do I configure cperl (or is it possible?) so that `cperl-indent-region` does not mess up the indentations within here-docs.

If I have something like,
```
print FILEHANDLE <<EOF;
$i : begin
   \$display("");
   `INFO1("abcd");
   config_this (
      .abc(abcd));
EOF
```
, after cperl indentation it becomes this,
```
print FILEHANDLE <<EOF;
$i : begin
\$display("");
`INFO1("abcd");
config_this (
.abc(abcd));
EOF
```
How do I prevent that? 
I am using cperl version 20140309.122 from Melpa.

Thanks.

**Comment by TLINDEN** [comment]
Same problem with sample code inside a POD section.

**Comment by TLINDEN** [comment]
I switched to the stock cperl-mode which comes with emacs. It's now working like a charm. `cperl-indent-region` doesnt touch POD sections anymore.

**Comment by kaushalmodi** [comment]
@TLINDEN Thanks. I had lost track of this issue. I haven't seen this issue happening on the `cperl-mode` that ships with emacs.

**Comment by renormalist** [comment]
I merged the corresponding PR here. Tell me when I freaked up things.
