### ISSUE TITLE
problem in syntax highlighting for: split /\s+/, $string [v.= mxd-perl6-merge]

### ISSUE THREAD

**Issue by pamag** [jrockway/cperl-mode#5]
it takes 's+' as starting of substitution and wants another '+'

I am using branch mxd-perl6-merge

=snip for testing=

<pre>
#!/usr/bin/env perl

use strict;

my $string;
my $x = split /\s+/, $string;

# morestuff
my $nowaycolor;
</pre>

== end snp==

**Comment by renormalist** [comment]
I can't maintain that branch anymore, sorry. Closing for cleanup reasons.
